package com.example.fitbox;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.TypeConverters;
import java.util.Date;

@Entity(
        tableName = "activity_data",
        foreignKeys = {
                @ForeignKey(
                        entity = UserAccount.class,
                        parentColumns = "userId",
                        childColumns = "userId",
                        onDelete = ForeignKey.CASCADE
                ),
                @ForeignKey(
                        entity = ActivityInformation.class,
                        parentColumns = "activityId",
                        childColumns = "activityId",
                        onDelete = ForeignKey.CASCADE
                )
        },
        indices = {@Index("userId"), @Index("activityId")}
)
@TypeConverters(ActivityDateConverter.class)
public class ActivityData {
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "activityDataId") private long activityDataId;
    @ColumnInfo(name = "activityId") private long activityId; // Foreign Key
    @ColumnInfo(name = "userId") private long userId; // Foreign Key
    @ColumnInfo(name = "time_stamp", typeAffinity = ColumnInfo.TEXT) private Date timeStamp;
    @ColumnInfo(name = "activity") private String activity;

    public ActivityData(long userId,long activityId, String activity) {
        this.userId = userId;
        this.activityId = activityId;
        this.timeStamp = new Date(); // Automatically set the current timestamp
        this.activity = activity;
    }


    public long getActivityId() {
        return activityId;
    }

    public void setActivityDataId(long activityDataId) {
        this.activityDataId = activityDataId;
    }


    public long getActivityDataId() {
        return activityDataId;
    }

    public long getUserId() {
        return userId;
    }


    public void setActivityIdId(long autogeneratedId) {
        this.activityId = activityId;
    }

    public Date getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public String getActivity() {
        return activity;
    }

    public void setActivity(String activity) {
        this.activity = activity;
    }
}

